# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/assafmo/joincap
    steps:
      - checkout
      - run: go version
      - run: go get -v -t -d ./...
      - run: go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=./coverage.out ./...
      - run: $GOPATH/bin/goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
